# Generated by Django 5.0 on 2024-01-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Parent_ID', models.CharField(max_length=5, verbose_name='Parent ID')),
                ('Parent_Phone_Num', models.IntegerField(verbose_name='Parent Phone Number')),
                ('Parent_Username', models.CharField(max_length=50, verbose_name='Parent Username')),
                ('Parent_Password', models.CharField(max_length=50, verbose_name='Parent Password')),
                ('Parent_Email', models.EmailField(max_length=50, verbose_name='Parent Email')),
            ],
        ),
    ]
