# Generated by Django 5.0 on 2024-01-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_ID', models.CharField(max_length=5, verbose_name='Student ID')),
                ('Student_Name', models.CharField(max_length=50, verbose_name='Student Name')),
                ('Student_Gender', models.CharField(max_length=10, verbose_name='Student Gender')),
                ('Student_Race', models.CharField(max_length=10, verbose_name='Student Race')),
                ('Student_Grade', models.IntegerField(verbose_name='Student Grade')),
            ],
        ),
    ]
