# Generated by Django 5.0 on 2024-01-08 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenWorker',
            fields=[
                ('Worker_ID', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Worker ID')),
                ('Worker_Username', models.CharField(max_length=50, verbose_name='Canteen Worker Username')),
                ('Worker_Password', models.CharField(max_length=50, verbose_name='Canteen Worker Password')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('Food_ID', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Food ID')),
                ('Food_Name', models.CharField(max_length=50, verbose_name='Food Name')),
                ('Food_Price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Food Price')),
                ('Ingredient_List', models.TextField(max_length=100, verbose_name='Ingredient List')),
                ('Food_Description', models.TextField(max_length=200, verbose_name='Food ID')),
                ('Food_Category', models.CharField(max_length=10, verbose_name='Food ID')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('RequestFood_ID', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Request Food ID')),
                ('RequestFood_Name', models.CharField(max_length=50, verbose_name='Request Food Name')),
                ('RequestFood_Price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Request Food Price')),
                ('RequestIngredient_List', models.TextField(max_length=100, verbose_name='Request Ingredient List')),
                ('RequestFood_Description', models.TextField(max_length=200, verbose_name='Request Food Description')),
                ('RequestFood_Category', models.CharField(max_length=10, verbose_name='Request Food Category')),
                ('Request_Title', models.CharField(max_length=50, verbose_name='Request Title')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_ID',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Student ID'),
        ),
        migrations.AlterUniqueTogether(
            name='parent',
            unique_together={('Parent_ID', 'Parent_Email')},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_ID', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Order ID')),
                ('Order_Status', models.CharField(max_length=10, verbose_name='Order Status')),
                ('Food_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.fooditem')),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.student')),
            ],
        ),
    ]
