# Generated by Django 5.0 on 2024-01-16 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Worker_Username', models.CharField(max_length=50, verbose_name='Canteen Worker Username')),
                ('Worker_Password', models.CharField(max_length=50, verbose_name='Canteen Worker Password')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_Name', models.CharField(max_length=50, verbose_name='Food Name')),
                ('Food_Price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Food Price')),
                ('Ingredient_List', models.TextField(max_length=100, verbose_name='Ingredient List')),
                ('Food_Description', models.TextField(max_length=200, verbose_name='Food Description')),
                ('Food_Category', models.CharField(max_length=10, verbose_name='Food Category')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequestFood_Name', models.CharField(max_length=50, verbose_name='Request Food Name')),
                ('RequestFood_Price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Request Food Price')),
                ('RequestIngredient_List', models.TextField(max_length=100, verbose_name='Request Ingredient List')),
                ('RequestFood_Description', models.TextField(max_length=200, verbose_name='Request Food Description')),
                ('RequestFood_Category', models.CharField(max_length=10, verbose_name='Request Food Category')),
                ('Request_Title', models.CharField(max_length=50, verbose_name='Request Title')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_ID', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=50, verbose_name='Student Name')),
                ('Student_Gender', models.CharField(max_length=10, verbose_name='Student Gender')),
                ('Student_Race', models.CharField(max_length=10, verbose_name='Student Race')),
                ('Student_Grade', models.IntegerField(verbose_name='Student Grade')),
                ('Parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Status', models.CharField(max_length=10, verbose_name='Order Status')),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='practice.fooditem')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='practice.student')),
            ],
        ),
    ]
