# Generated by Django 5.0 on 2024-01-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_rename_status_request_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='Request_Status',
            field=models.CharField(max_length=10, verbose_name='Status'),
        ),
    ]
