# Generated by Django 5.0.1 on 2024-01-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0010_remove_request_request_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='Food_Category',
        ),
        migrations.RemoveField(
            model_name='request',
            name='RequestFood_Category',
        ),
    ]
