# Generated by Django 5.0.1 on 2024-02-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0013_orderitem_delete_canteenworker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='Food_Availability',
            field=models.BooleanField(default=True, verbose_name='Food Availability'),
        ),
    ]
